# permissions for end users to edit podmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podmanager-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-manager-operator
    app.kubernetes.io/part-of: pod-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: podmanager-editor-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - podmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - podmanagers/status
  verbs:
  - get
